### ISSUE TITLE
Model Not Working because of missing files

### ISSUE THREAD

**Issue by DeepakNandi** [cansyl/SLPred#1]
When installing the the tool it is running fine up-to the execution of 
./download_extract_data.sh
but after that two files that are received namely saved_models.zip and Trust_all_data.zip are either corrupted or empty as we receive this error 
$ unzip saved_models.zip
Archive:  saved_models.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of saved_models.zip or
        saved_models.zip.zip, and cannot find saved_models.zip.ZIP, period.
and 
$ unzip Trust_all_data.zip
Archive:  Trust_all_data.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Trust_all_data.zip or
        Trust_all_data.zip.zip, and cannot find Trust_all_data.zip.ZIP, period. 

for this reason the model is mot working anad producing the error :
$ python run_SLPred.py --file 1923cdhit
Preprocessing module is running...
Position-specific-scoring matrices are being generated...

Prediction module is running...
**Traceback (most recent call last):
  File "run_SLPred.py", line 26, in <module>
    dict_prot_id_loc_predictions = predict_sub_locs(feature_directory, file_name)
  File "/home/t7400/deepak_nandi/1923_analysis/SLPred/predict_sub_locs.py", line 96, in predict_sub_locs
    dict_locs_threshold_weights = read_threshold_weights()
  File "/home/t7400/deepak_nandi/1923_analysis/SLPred/load_saved_models.py", line 10, in read_threshold_weights
    with open(directory+loc+"_saved_models/"+loc+"_threshold_model_weights.txt", "r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'saved_models/CYT_saved_models/CYT_threshold_model_weights.txt'**

Please see to this matter and upload the correct files ASAP.
Regards

**Comment by gozsari** [comment]
I've updated the links and tested them; everything appears to be working as expected. Please let me know if you encounter any issues again.
